// <auto-generated />
namespace Customer.Data.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class partyContactEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partyContactEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202308271814346_partyContactEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
