// <auto-generated />
namespace Customer.Data.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deletingExtraFieldMaterialEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletingExtraFieldMaterialEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202310081817576_deletingExtraFieldMaterialEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
