// <auto-generated />
namespace Customer.Data.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PermissionNModuleEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PermissionNModuleEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202311220028220_PermissionNModuleEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
